### ISSUE TITLE
Improve support for autofs direct maps

### ISSUE THREAD

**Issue by citnfm** [robertdebock/ansible-role-autofs#6]
## Proposed feature

In order to improve the support for direct maps in the role 2 features (changes) should be added:
1. Skip the creation of the `mountpoint` if it is a direct map. (the `mountpoint` on direct maps is `/-`)
2. Add the option to include a `name` for the map. This will be used in the file names if available and default to the `mountpoint`.

## Rationale
Autofs has two types of maps, [direct and indirect](https://docs.oracle.com/cd/E19683-01/816-7125/6md5dso2l/index.html). When using a direct map the `mountpoint` is `/-` and in the current state of the role, it will create the `/-` folder of the direct map and output the following files:
```
/etc/auto.-
/etc/auto.master.d/00--.autofs
```

When using a direct map the `mountpoint` does not need to exist as a folder on the system so a condition should be added to the task to skip the folder creation when the `mountpount` is `/-`

Then to improve the naming of the generated files, a `name` key should be added as an option in the map configuration. The `name` will be used in the filenames if available then default to `mountpoint` (this will provide backwards compatibility). For example the following `autofs_maps` will produce the following files:
```YAML
autofs_maps:
  - name: direct-mounts
    mountpoint: /-
    options:
      - "--timeout 60"
      - "--ghost"
    directories:
      - path: /bind/direct/mount
        server: ":/mnt"
        options:
          - "fstype=bind"
```
```
/etc/auto.direct-mounts
/etc/auto.master.d/00-direct-mounts.autofs
```

## Additional context

I will be creating a pull request with my suggestion on how to approach this within the role.
